export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const ON_PAGE_CHANGED_ACTION = "ON_PAGE_CHANGED_ACTION";
export const RANGE = "RANGE";
export const ON_CHANGE_CURRENT_PAGE = "ON_CHANGE_CURRENT_PAGE";
export const CHANGE_PAGE_LIMIT = "CHANGE_PAGE_LIMIT";
